require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/bundle/**/*
    - 'db/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - 'config/**/*'
Layout/LineLength:
  Max: 160
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
