require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'config/'
    - 'node_modules/**/*'
    - 'config/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
