default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: rails-project-64_development

test:
  <<: *default
  database: rails-project-64_test

production:
  <<: *default
  database: rails-project-64_production
