default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails-project-64_development

# test:
#   <<: *default
#   database: rails-project-64_test

test:
  adapter: sqlite3
  database: db/rails-project-64_test.sqlite3

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] %>
